# Generated by Django 4.1.3 on 2025-12-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_bnpluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the item being traded in')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
