# Generated by Django 4.1.3 on 2025-10-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0718693484', max_length=20),
            preserve_default=False,
        ),
    ]
