# Generated by Django 4.1.3 on 2025-10-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_location_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this user can manage other users in their location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider'), ('admin', 'Admin'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='service_location',
            field=models.ForeignKey(blank=True, help_text='Location where staff member works', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='users.location'),
        ),
    ]
