# Generated by Django 4.1.3 on 2025-11-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_location_user_is_location_admin_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pickup_address',
            field=models.TextField(blank=True, help_text='Default pickup address for service bookings', null=True),
        ),
    ]
