# Generated by Django 5.0.14 on 2026-02-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_passwordresetcode'),
        ('users', '0008_alter_user_phone_passwordresetcode'),
    ]

    operations = [
    ]
