# Generated by Django 4.1.3 on 2025-12-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamewallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='gamewallet',
            name='total_deposits',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='gamewallet',
            name='total_losses',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='gamewallet',
            name='total_winnings',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
