# Generated by Django 4.1.3 on 2025-12-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0002_alter_gamewallet_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinAlgorithmConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this algorithm configuration', max_length=100, unique=True)),
                ('algorithm_key', models.CharField(choices=[('balanced', 'Balanced'), ('conservative', 'Conservative'), ('generous', 'Generous'), ('peak_hour', 'Peak Hour'), ('late_night', 'Late Night')], help_text='Which algorithm to use', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Only one algorithm can be active at a time')),
                ('start_time', models.TimeField(blank=True, help_text='Time to auto-activate this algorithm (optional)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Time to deactivate this algorithm (optional)', null=True)),
                ('days_of_week', models.CharField(default='0,1,2,3,4,5,6', help_text='Comma-separated day numbers: 0=Mon, 6=Sun', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of when/why to use this algorithm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spin Algorithm Configuration',
                'verbose_name_plural': 'Spin Algorithm Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
