# Generated by Django 4.1.3 on 2025-12-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0004_gamespinresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamespinresult',
            new_name='casino_game_wallet__a312d9_idx',
            old_name='casino_game_wallet_created_idx',
        ),
        migrations.RenameIndex(
            model_name='gamespinresult',
            new_name='casino_game_wallet__bac03e_idx',
            old_name='casino_game_wallet_type_idx',
        ),
        migrations.RenameIndex(
            model_name='gamespinresult',
            new_name='casino_game_is_win_9bd6e1_idx',
            old_name='casino_game_is_win_idx',
        ),
        migrations.AlterField(
            model_name='spinalgorithmconfiguration',
            name='algorithm_key',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('conservative', 'Conservative'), ('generous', 'Generous'), ('peak_hour', 'Peak Hour'), ('late_night', 'Late Night'), ('aggressive_losing_streak', 'Aggressive Losing Streak')], help_text='Which algorithm to use', max_length=50),
        ),
    ]
