# Generated by Django 5.0.14 on 2026-02-20 01:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('annual_return_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_annual_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_monthly_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_received_returns', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('lockup_period_months', models.IntegerField()),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', models.DateTimeField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('next_payout_date', models.DateTimeField(blank=True, null=True)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('payout_frequency', models.CharField(default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
