# Generated by Django 4.1.3 on 2025-10-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('laundry', 'Laundry'), ('duvet', 'Duvet Cleaning'), ('carpet', 'Carpet Cleaning'), ('house', 'House Cleaning'), ('fumigation', 'Fumigation'), ('installation', 'TV Mounting & Hot Shower Installation')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
