# Generated by Django 5.2.7 on 2025-11-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image', null=True, upload_to='services/'),
        ),
    ]
