# Generated by Django 4.1.3 on 2025-12-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_losses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Wallet',
                'verbose_name_plural': 'Game Wallets',
            },
        ),
        migrations.CreateModel(
            name='GameTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('debit', 'Debit (Game Play)'), ('credit', 'Credit (Winnings)'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(help_text="e.g., 'mpesa', 'game_play', 'game_winnings', etc.", max_length=100)),
                ('payment_id', models.PositiveIntegerField(blank=True, help_text='Reference to Payment model if from payment', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='games.gamewallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gametransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='games_gamet_wallet__67fe67_idx'),
        ),
        migrations.AddIndex(
            model_name='gametransaction',
            index=models.Index(fields=['transaction_type'], name='games_gamet_transac_f2bdc4_idx'),
        ),
    ]
