# Generated by Django 4.1.3 on 2025-10-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_location_user_is_location_admin_alter_user_role_and_more'),
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_location',
            field=models.ForeignKey(blank=True, help_text='The location where this order is being processed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.location'),
        ),
    ]
