# Generated by Django 5.2.7 on 2025-11-14 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_rider'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders', to='services.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_orders', to='services.service'),
        ),
    ]
