# Generated by Django 5.2.7 on 2025-11-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_orders_orde_user_id_0ae59f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text="Rider's notes about the order", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Quantity of items picked up by rider', null=True),
        ),
    ]
