# Generated by Django 4.1.3 on 2025-11-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_description_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
