# Generated by Django 4.1.3 on 2025-11-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual price paid for the order recorded by staff', max_digits=10, null=True),
        ),
    ]
