# Generated by Django 4.1.3 on 2025-12-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_order_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who created this manual order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for manual/walk-in orders', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name for manual/walk-in orders', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone for manual/walk-in orders', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='drop_off_type',
            field=models.CharField(choices=[('delivery', 'Customer Delivery'), ('walk_in', 'Walk-in Customer'), ('phone', 'Phone Order')], default='delivery', help_text='How the order was dropped off/created', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('online', 'Online Order'), ('manual', 'Staff-Created Order')], default='online', help_text='Whether order was created online or manually by staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('picked', 'Picked Up'), ('in_progress', 'In Progress'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('pending_assignment', 'Pending Assignment')], default='requested', max_length=20),
        ),
    ]
