# Generated by Django 4.1.3 on 2025-12-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_created_by_order_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
    ]
