# Generated by Django 4.1.3 on 2025-11-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('new_order', 'New Order'), ('order_assigned', 'Order Assigned')], default='order_update', help_text='Type of notification for filtering', max_length=20),
        ),
    ]
